repo_url: https://github.com/west7/EDA2
repo_name: EDA2

site_name: Estrutura de dados e algoritmos
site_url: https://west7.github.io/EDA2
site_author: GUilherme Westphall
site_description: Site destinado à documentação da apostila de estrutura de dados 2.

nav:
  - Início:
    - Sumário: index.md
    - Hash Table: apostila/HashTable.md
    - Árvore Red Black: apostila/ÁrvoreRedBlack.md
    - Fila de Prioridades: apostila/FiladePrioridades.md
    - Grafos: apostila/Grafos.md
    - Quickselect: apostila/Quickselect.md


theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
  palette:
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Mudar para o modo escuro
      primary: black
      accent: red

    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Mudar para o modo claro
      primary: black
      accent: red
  language: pt-BR

plugins:
  - search
  - mermaid2

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.mark
  - attr_list
  - pymdownx.superfences

       


