repo_url: https://github.com/west7/EDA2
repo_name: EDA2

site_name: Estrutura de dados e algoritmos
site_url: https://west7.github.io/EDA2
site_author: GUilherme Westphall
site_description: Site destinado à documentação da apostila de estrutura de dados 2.

nav:
  - Início:
    - Sumário: index.md
  - Apostila:
    - Hash Table: apostila/HashTable.md
    - Árvore Red Black: apostila/ÁrvoreRedBlack.md
    - Fila de Prioridades: apostila/FiladePrioridades.md
    - Grafos: apostila/Grafos.md
    - Quickselect: apostila/Quickselect.md
  - Listas:
    - Lista 1: exec/01_desenferrujando.md
    - Lista 2: exec/02_hashing.md
    - Lista 3: exec/03_priority_queue.md
    - Lista 4: exec/04_quickselect.md
    - Lista 5: exec/05_grafos.md
    - Lista 6: exec/06_busca_em_grafos.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Mudar para o modo escuro
      primary: black
      accent: deep purple

    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Mudar para o modo claro
      primary: black
      accent: deep purple
  language: pt-BR
  
extra_css:
  - style/style.css


plugins:
  - search
  - include-markdown

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.mark
  - attr_list
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format

        
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js

extra:
  social: 

